import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    slug: "carrara-white-marble",
    name: "Carrara White Marble",
    category: "marble",
    finish: "polished",
    price: 10,
    unit: "sqft",
    images: [
      "/images/Exotic-Travertine-Ivory-Stripe-qxti2zc4r56gc8v6pnujh77ae4t684kdfhln9no0w0.jpg",
      "/images/slider-qxbxlb1pnn7lnr37mcfhy1qfctmztsja829dgwhocg.jpg",
      "/images/sansam-mobile-slider2.jpg",
    ],
  },
  {
    id: 2,
    slug: "black-galaxy-granite",
    name: "Black Galaxy Granite",
    category: "granite",
    finish: "polished",
    price: 10,
    unit: "sqft",
    images: [
      "/images/lava-blue.jpg",
      "/images/slider-lava-blue.jpg",
      "/images/Prong-768x1024.webp",
    ],
  },
  {
    id: 3,
    slug: "calacatta-gold-marble",
    name: "Calacatta Gold Marble",
    category: "marble",
    finish: "honed",
    price: 10,
    unit: "sqft",
    images: [
      "/images/slider-qxbxlb1pnn7lnr37mcfhy1qfctmztsja829dgwhocg.jpg",
      "/images/Exotic-Travertine-Ivory-Stripe-qxti2zc4r56gc8v6pnujh77ae4t684kdfhln9no0w0.jpg",
      "/images/cottage-tile.jpg",
    ],
  },
  {
    id: 4,
    slug: "kashmir-white-granite",
    name: "Kashmir White Granite",
    category: "granite",
    finish: "polished",
    price: 10,
    unit: "sqft",
    images: [
      "/images/slider-lava-blue.jpg",
      "/images/lava-blue.jpg",
      "/images/concept-light-gray-.jpg",
    ],
  },
  {
    id: 5,
    slug: "emperador-brown-marble",
    name: "Emperador Brown Marble",
    category: "marble",
    finish: "polished",
    price: 10,
    unit: "sqft",
    images: [
      "/images/sansam-mobile-slider.jpg",
      "/images/sansam-mobile-slider2.jpg",
      "/images/cottage-tile.jpg",
    ],
  },
  {
    id: 6,
    slug: "absolute-black-granite",
    name: "Absolute Black Granite",
    category: "granite",
    finish: "leather",
    price: 20,
    unit: "sqft",
    images: [
      "/images/Prong-768x1024.webp",
      "/images/lava-blue.jpg",
      "/images/slider-lava-blue.jpg",
    ],
  },
  {
    id: 7,
    slug: "modern-grey-ceramic",
    name: "Modern Grey Ceramic",
    category: "ceramic",
    finish: "matte",
    price: 30,
    unit: "sqft",
    images: [
      "/images/concept-light-gray-.jpg",
      "/images/cottage.jpg",
      "/images/cottage-tile.jpg",
    ],
  },
  {
    id: 8,
    slug: "travertine-beige",
    name: "Travertine Beige",
    category: "marble",
    finish: "honed",
    price: 30,
    unit: "sqft",
    images: [
      "/images/cottage-tile.jpg",
      "/images/Exotic-Travertine-Ivory-Stripe-qxti2zc4r56gc8v6pnujh77ae4t684kdfhln9no0w0.jpg",
      "/images/sansam-mobile-slider.jpg",
    ],
  },
  {
    id: 9,
    slug: "porcelain-wood-look",
    name: "Porcelain Wood Look",
    category: "porcelain",
    finish: "textured",
    price: 30,
    unit: "sqft",
    images: [
      "/images/cottage.jpg",
      "/images/cottage-tile.jpg",
      "/images/concept-light-gray-.jpg",
    ],
  },
  {
    id: 10,
    slug: "statuario-marble",
    name: "Statuario Marble",
    category: "marble",
    finish: "polished",
    price: 30,
    unit: "sqft",
    images: [
      "/images/sansam-mobile-slider2.jpg",
      "/images/sansam-mobile-slider.jpg",
      "/images/slider-qxbxlb1pnn7lnr37mcfhy1qfctmztsja829dgwhocg.jpg",
    ],
  },
  {
    id: 11,
    slug: "blue-pearl-granite",
    name: "Blue Pearl Granite",
    category: "granite",
    finish: "polished",
    price: 30,
    unit: "sqft",
    images: [
      "/images/lava-blue.jpg",
      "/images/Prong-768x1024.webp",
      "/images/slider-lava-blue.jpg",
    ],
  },
  {
    id: 12,
    slug: "concrete-look-porcelain",
    name: "Concrete Look Porcelain",
    category: "porcelain",
    finish: "matte",
    price: 40,
    unit: "sqft",
    images: [
      "/images/concept-light-gray-.jpg",
      "/images/cottage.jpg",
      "/images/Prong-768x1024.webp",
    ],
  },
];

export const categories = ["marble", "granite", "ceramic", "porcelain"];
export const finishes = ["polished", "honed", "matte", "leather", "textured"];
