import { Product } from "./types";

export const products: Product[] = [
  // Stone Look Collection - Travertine Series
  {
    id: 1,
    slug: "trava-bone",
    name: "Trava Bone",
    code: "91300",
    category: "stone-look",
    finish: "matt",
    price: 45,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Travertine-inspired porcelain with natural bone tones and authentic texture",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
    ],
  },
  {
    id: 2,
    slug: "exotic-travertine-beige-stripe",
    name: "Exotic Travertine Beige Stripe",
    code: "91400",
    category: "stone-look",
    finish: "polished",
    price: 50,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Premium travertine look with distinctive stripe pattern in beige tones",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
    ],
  },
  {
    id: 3,
    slug: "exotic-travertine-beige-natural",
    name: "Exotic Travertine Beige Natural",
    code: "91400",
    category: "stone-look",
    finish: "polished",
    price: 50,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Premium travertine look with natural finish in beige tones",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
    ],
  },
  {
    id: 4,
    slug: "exotic-travertine-ivory-stripe",
    name: "Exotic Travertine Ivory Stripe",
    code: "92500",
    category: "stone-look",
    finish: "polished",
    price: 50,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Premium travertine look with distinctive stripe pattern in ivory tones",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
    ],
  },
  {
    id: 5,
    slug: "exotic-travertine-ivory-natural",
    name: "Exotic Travertine Ivory Natural",
    code: "92500",
    category: "stone-look",
    finish: "polished",
    price: 50,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Premium travertine look with natural finish in ivory tones",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
    ],
  },
  // Stone Look Collection - Rockstone Series
  {
    id: 6,
    slug: "rockstone-dark-gray-slate",
    name: "Rockstone Dark Gray Slate",
    code: "92200",
    category: "stone-look",
    finish: "matt",
    price: 48,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Exterior", "Residential", "Commercial"],
    description: "Bold dark gray slate-inspired porcelain with natural stone texture",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
    ],
  },
  {
    id: 7,
    slug: "rockstone-dark-gray-natural",
    name: "Rockstone Dark Gray Natural",
    code: "92200",
    category: "stone-look",
    finish: "matt",
    price: 48,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Exterior", "Residential", "Commercial"],
    description: "Dark gray natural stone look porcelain with authentic texture",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
    ],
  },
  {
    id: 8,
    slug: "rockstone-ivory-slate",
    name: "Rockstone Ivory Slate",
    code: "92100",
    category: "stone-look",
    finish: "matt",
    price: 48,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Interior", "Residential", "Commercial"],
    description: "Elegant ivory slate-inspired porcelain with natural stone texture",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
    ],
  },
  {
    id: 9,
    slug: "rockstone-ivory-natural",
    name: "Rockstone Ivory Natural",
    code: "92100",
    category: "stone-look",
    finish: "matt",
    price: 48,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Interior", "Residential", "Commercial"],
    description: "Ivory natural stone look porcelain with authentic texture",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
    ],
  },
  // Stone Look Collection - Ceppo Series
  {
    id: 10,
    slug: "ceppo-light-gray",
    name: "Ceppo Light Gray",
    code: "79100",
    category: "stone-look",
    finish: "polished",
    price: 52,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Contemporary light gray ceppo stone-inspired porcelain",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
    ],
  },
  {
    id: 11,
    slug: "ceppo-dark-gray",
    name: "Ceppo Dark Gray",
    code: "79200",
    category: "stone-look",
    finish: "polished",
    price: 52,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Bold dark gray ceppo stone-inspired porcelain",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
    ],
  },
  // Marble Look Collection - Black Collection
  {
    id: 12,
    slug: "lava-black",
    name: "Lava Black",
    code: "76300",
    category: "marble-look",
    finish: "polished",
    price: 65,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Countertops", "Residential", "Commercial"],
    description: "Dramatic black marble look with subtle veining, perfect for luxury spaces",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
    ],
  },
  {
    id: 13,
    slug: "lava-black-matt",
    name: "Lava Black Matt",
    code: "76300",
    category: "marble-look",
    finish: "matt",
    price: 65,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Dramatic black marble look with matt finish for contemporary elegance",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
    ],
  },
  {
    id: 14,
    slug: "black-marquina",
    name: "Black Marquina",
    code: "74800",
    category: "marble-look",
    finish: "polished",
    price: 70,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Countertops", "Residential", "Commercial"],
    description: "Classic black Marquina marble look with white veining, perfect for bookmatch installations",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
    ],
  },
  {
    id: 15,
    slug: "black-marquina-matt",
    name: "Black Marquina Matt",
    code: "74800",
    category: "marble-look",
    finish: "matt",
    price: 70,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Classic black Marquina marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
    ],
  },
  {
    id: 16,
    slug: "lava-gray",
    name: "Lava Gray",
    code: "76400",
    category: "marble-look",
    finish: "polished",
    price: 75,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Countertops", "Residential", "Commercial"],
    description: "Sophisticated gray marble look with dynamic veining patterns",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
    ],
  },
  {
    id: 17,
    slug: "lava-gray-matt",
    name: "Lava Gray Matt",
    code: "76400",
    category: "marble-look",
    finish: "matt",
    price: 75,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Sophisticated gray marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
    ],
  },
  // Marble Look Collection - Luxury Range
  {
    id: 18,
    slug: "lava-blue",
    name: "Lava Blue",
    code: "76200",
    category: "marble-look",
    finish: "polished",
    price: 75,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Countertops", "Residential", "Commercial"],
    description: "Striking blue marble look with dramatic veining, ideal for luxury installations",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
    ],
  },
  {
    id: 19,
    slug: "onyx-blue",
    name: "Onyx Blue",
    code: "78300",
    category: "marble-look",
    finish: "polished",
    price: 80,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Walls", "Feature Walls", "Backsplashes", "Residential", "Commercial"],
    description: "Exotic blue onyx marble look with translucent qualities and unique patterns",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
    ],
  },
  {
    id: 20,
    slug: "onyx-white",
    name: "Onyx White",
    code: "78200",
    category: "marble-look",
    finish: "polished",
    price: 80,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Walls", "Backsplashes", "Residential", "Commercial"],
    description: "Elegant white onyx marble look with subtle veining and translucency",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
    ],
  },
  // Marble Look Collection - Classic Marbles
  {
    id: 21,
    slug: "statuario",
    name: "Statuario",
    code: "67400",
    category: "marble-look",
    finish: "polished",
    price: 70,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Feature Walls", "Residential", "Commercial"],
    description: "Timeless white Statuario marble look with elegant gray veining",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
    ],
  },
  {
    id: 22,
    slug: "statuario-matt",
    name: "Statuario Matt",
    code: "67400",
    category: "marble-look",
    finish: "matt",
    price: 70,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Timeless white Statuario marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
    ],
  },
  {
    id: 23,
    slug: "statuario-clara",
    name: "Statuario Clara",
    code: "67400",
    category: "marble-look",
    finish: "polished",
    price: 72,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Light Statuario marble variant with subtle veining in large format",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
    ],
  },
  {
    id: 24,
    slug: "carrara",
    name: "Carrara",
    code: "62600",
    category: "marble-look",
    finish: "polished",
    price: 65,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Classic Carrara white marble look with soft gray veining",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
    ],
  },
  {
    id: 25,
    slug: "carrara-matt",
    name: "Carrara Matt",
    code: "62600",
    category: "marble-look",
    finish: "matt",
    price: 65,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Classic Carrara white marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
    ],
  },
  {
    id: 26,
    slug: "calacatta-gold",
    name: "Calacatta Gold",
    code: "71400",
    category: "marble-look",
    finish: "polished",
    price: 85,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Feature Walls", "Residential", "Commercial"],
    description: "Luxurious Calacatta Gold marble look with distinctive gold veining",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
    ],
  },
  {
    id: 27,
    slug: "calacatta-gold-matt",
    name: "Calacatta Gold Matt",
    code: "71400",
    category: "marble-look",
    finish: "matt",
    price: 85,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Luxurious Calacatta Gold marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
    ],
  },
  {
    id: 28,
    slug: "arabescato",
    name: "Arabescato",
    code: "72100",
    category: "marble-look",
    finish: "polished",
    price: 70,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Elegant Arabescato marble look with characteristic gray and white patterns",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
    ],
  },
  {
    id: 29,
    slug: "arabescato-matt",
    name: "Arabescato Matt",
    code: "72100",
    category: "marble-look",
    finish: "matt",
    price: 70,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Elegant Arabescato marble look with matt finish",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
    ],
  },
  // Marble Look Collection - Designer Marbles
  {
    id: 30,
    slug: "alma",
    name: "Alma",
    code: "72400",
    category: "marble-look",
    finish: "polished",
    price: 75,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Walls", "Feature Walls", "Backsplashes", "Residential", "Commercial"],
    description: "Designer marble look with unique patterns, perfect for bookmatch installations",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
    ],
  },
  {
    id: 31,
    slug: "ariston",
    name: "Ariston",
    code: "63600",
    category: "marble-look",
    finish: "polished",
    price: 72,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Premium Ariston marble look with elegant veining, bookmatch available",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
    ],
  },
  {
    id: 32,
    slug: "ariston-matt",
    name: "Ariston Matt",
    code: "63600",
    category: "marble-look",
    finish: "matt",
    price: 72,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    bookmatch: true,
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Premium Ariston marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
    ],
  },
  {
    id: 33,
    slug: "gemma",
    name: "Gemma",
    code: "68800",
    category: "marble-look",
    finish: "polished",
    price: 74,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Sophisticated Gemma marble look with refined patterns",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
    ],
  },
  {
    id: 34,
    slug: "gemma-matt",
    name: "Gemma Matt",
    code: "68800",
    category: "marble-look",
    finish: "matt",
    price: 74,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Sophisticated Gemma marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
    ],
  },
  {
    id: 35,
    slug: "marmo-dorato",
    name: "Marmo Dorato",
    code: "66100",
    category: "marble-look",
    finish: "matt",
    price: 76,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Golden marble look with warm tones and elegant patterns",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
    ],
  },
  {
    id: 36,
    slug: "royal-gold",
    name: "Royal Gold",
    code: "61700",
    category: "marble-look",
    finish: "polished",
    price: 88,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Walls", "Countertops", "Residential", "Commercial"],
    description: "Luxurious royal gold marble look with opulent veining",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
    ],
  },
  {
    id: 37,
    slug: "royal-gold-matt",
    name: "Royal Gold Matt",
    code: "61700",
    category: "marble-look",
    finish: "matt",
    price: 88,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Walls", "Residential", "Commercial"],
    description: "Luxurious royal gold marble look with matt finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
    ],
  },
  {
    id: 38,
    slug: "elegant-beige",
    name: "Elegant Beige",
    code: "61200",
    category: "marble-look",
    finish: "polished",
    price: 68,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Warm beige marble look with subtle veining and elegant appearance",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
    ],
  },
  {
    id: 39,
    slug: "elegant-beige-matt",
    name: "Elegant Beige Matt",
    code: "61200",
    category: "marble-look",
    finish: "matt",
    price: 68,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Warm beige marble look with matt finish",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
    ],
  },
  {
    id: 40,
    slug: "verde",
    name: "Verde",
    code: "86100",
    category: "marble-look",
    finish: "polished",
    price: 82,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Walls", "Backsplashes", "Residential", "Commercial"],
    description: "Unique green marble look with distinctive veining patterns",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
    ],
  },
  {
    id: 41,
    slug: "onici",
    name: "Onici",
    code: "68200",
    category: "marble-look",
    finish: "polished",
    price: 79,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Walls", "Backsplashes", "Residential", "Commercial"],
    description: "Exotic onyx-inspired marble look with unique patterns",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
    ],
  },
  {
    id: 42,
    slug: "amani-light-gray",
    name: "Amani Light Gray",
    code: "70600",
    category: "marble-look",
    finish: "polished",
    price: 71,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Countertops", "Residential", "Commercial"],
    description: "Sophisticated light gray Amani marble look with refined veining",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
    ],
  },
  // Modern Look Collection - Emerald Series
  {
    id: 43,
    slug: "emerald-ivory",
    name: "Emerald Ivory",
    code: "77200",
    category: "modern-look",
    finish: "matt",
    price: 55,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Contemporary ivory finish with modern aesthetics, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
    ],
  },
  {
    id: 44,
    slug: "emerald-light-gray",
    name: "Emerald Light Gray",
    code: "73800",
    category: "modern-look",
    finish: "matt",
    price: 55,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Contemporary light gray finish with modern aesthetics, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
    ],
  },
  {
    id: 45,
    slug: "emerald-light-gray-forest",
    name: "Emerald Light Gray Forest",
    code: "73801",
    category: "modern-look",
    finish: "matt",
    price: 58,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Areas", "Residential", "Commercial"],
    description: "Emerald Light Gray with forest décor pattern, perfect for feature areas",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
    ],
  },
  {
    id: 46,
    slug: "emerald-green",
    name: "Emerald Green",
    code: "65200",
    category: "modern-look",
    finish: "matt",
    price: 55,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Vibrant green finish with modern aesthetics, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
    ],
  },
  {
    id: 47,
    slug: "emerald-green-tropical",
    name: "Emerald Green Tropical",
    code: "65201",
    category: "modern-look",
    finish: "matt",
    price: 58,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Areas", "Residential", "Commercial"],
    description: "Emerald Green with tropical décor pattern, ideal for vibrant spaces",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
    ],
  },
  // Modern Look Collection - Monocolor Range
  {
    id: 48,
    slug: "monocolor-white",
    name: "Monocolor White",
    code: "55000",
    category: "modern-look",
    finish: "matt",
    price: 45,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Pure white monocolor porcelain for minimalist contemporary spaces",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
    ],
  },
  {
    id: 49,
    slug: "monocolor-light-gray",
    name: "Monocolor Light Gray",
    code: "55100",
    category: "modern-look",
    finish: "matt",
    price: 45,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Light gray monocolor porcelain for modern minimalist designs",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
    ],
  },
  {
    id: 50,
    slug: "monocolor-gray",
    name: "Monocolor Gray",
    code: "55200",
    category: "modern-look",
    finish: "matt",
    price: 45,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Mid gray monocolor porcelain for contemporary spaces",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
    ],
  },
  {
    id: 51,
    slug: "monocolor-dark-gray",
    name: "Monocolor Dark Gray",
    code: "55300",
    category: "modern-look",
    finish: "matt",
    price: 45,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Dark gray monocolor porcelain for bold contemporary designs",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
    ],
  },
  {
    id: 52,
    slug: "monocolor-anthracite",
    name: "Monocolor Anthracite",
    code: "55400",
    category: "modern-look",
    finish: "matt",
    price: 47,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Deep anthracite monocolor porcelain for dramatic modern spaces",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
    ],
  },
  // Modern Look Collection - Tattoo Series
  {
    id: 53,
    slug: "tattoo-light-gray",
    name: "Tattoo Light Gray",
    code: "65800",
    category: "modern-look",
    finish: "matt",
    price: 52,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Light gray with subtle pattern texture, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
    ],
  },
  {
    id: 54,
    slug: "tattoo-ivory",
    name: "Tattoo Ivory",
    code: "66200",
    category: "modern-look",
    finish: "matt",
    price: 52,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Ivory with subtle pattern texture, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
    ],
  },
  {
    id: 55,
    slug: "tattoo-anthracite",
    name: "Tattoo Anthracite",
    code: "65400",
    category: "modern-look",
    finish: "matt",
    price: 52,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Anthracite with subtle pattern texture, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
    ],
  },
  // Modern Look Collection - Concept Series
  {
    id: 56,
    slug: "concept-ivory",
    name: "Concept Ivory",
    code: "73300",
    category: "modern-look",
    finish: "matt",
    price: 50,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Contemporary ivory concept design, 6-face finish",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
    ],
  },
  {
    id: 57,
    slug: "concept-light-gray",
    name: "Concept Light Gray",
    code: "73600",
    category: "modern-look",
    finish: "matt",
    price: 50,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Contemporary light gray concept design, 6-face finish",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
    ],
  },
  {
    id: 58,
    slug: "concept-dark-gray",
    name: "Concept Dark Gray",
    code: "73700",
    category: "modern-look",
    finish: "matt",
    price: 50,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Contemporary dark gray concept design, 6-face finish",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
    ],
  },
  // Concept Stripe Designs
  {
    id: 59,
    slug: "concept-light-gray-stripe",
    name: "Concept Light Gray Stripe",
    code: "73602",
    category: "modern-look",
    finish: "matt",
    price: 53,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Areas", "Residential", "Commercial"],
    description: "Concept Light Gray with stripe pattern for contemporary feature areas",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
    ],
  },
  {
    id: 60,
    slug: "concept-pink-stripe",
    name: "Concept Pink Stripe",
    code: "73200",
    category: "modern-look",
    finish: "matt",
    price: 53,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Residential", "Commercial"],
    description: "Contemporary pink stripe pattern for vibrant feature areas",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
    ],
  },
  {
    id: 61,
    slug: "concept-blue-stripe",
    name: "Concept Blue Stripe",
    code: "73201",
    category: "modern-look",
    finish: "matt",
    price: 53,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Residential", "Commercial"],
    description: "Contemporary blue stripe pattern for modern feature areas",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
    ],
  },
  {
    id: 62,
    slug: "concept-green-stripe",
    name: "Concept Green Stripe",
    code: "73202",
    category: "modern-look",
    finish: "matt",
    price: 53,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Residential", "Commercial"],
    description: "Contemporary green stripe pattern for vibrant feature areas",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
    ],
  },
  {
    id: 63,
    slug: "concept-ivory-stripe",
    name: "Concept Ivory Stripe",
    code: "73301",
    category: "modern-look",
    finish: "matt",
    price: 53,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Floors", "Walls", "Feature Areas", "Residential", "Commercial"],
    description: "Concept Ivory with stripe pattern for contemporary feature areas",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
    ],
  },
  // Decorative Designs - Evo Dry Technology
  {
    id: 64,
    slug: "decorative-ocean",
    name: "Ocean - Evo Dry Technology",
    code: "6901",
    category: "decorative",
    finish: "matt",
    price: 60,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Bathrooms", "Wet Areas", "Residential", "Commercial"],
    description: "Ocean-inspired decorative design with Evo Dry Technology for enhanced performance in wet areas",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
    ],
  },
  {
    id: 65,
    slug: "decorative-azalea",
    name: "Azalea - Evo Dry Technology",
    code: "6900",
    category: "decorative",
    finish: "matt",
    price: 60,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Bathrooms", "Wet Areas", "Residential", "Commercial"],
    description: "Floral azalea-inspired decorative design with Evo Dry Technology",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
    ],
  },
  {
    id: 66,
    slug: "decorative-sunshine",
    name: "Sunshine - Evo Dry Technology",
    code: "6902",
    category: "decorative",
    finish: "matt",
    price: 60,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Bathrooms", "Wet Areas", "Residential", "Commercial"],
    description: "Bright sunshine-inspired decorative design with Evo Dry Technology",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
    ],
  },
  {
    id: 67,
    slug: "decorative-flower-garden",
    name: "Flower Garden - Evo Dry Technology",
    code: "6903",
    category: "decorative",
    finish: "matt",
    price: 60,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Bathrooms", "Wet Areas", "Residential", "Commercial"],
    description: "Garden-inspired decorative design with Evo Dry Technology",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
    ],
  },
  {
    id: 68,
    slug: "decorative-historical-green",
    name: "Historical Green - Evo Dry Technology",
    code: "6904",
    category: "decorative",
    finish: "matt",
    price: 62,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Bathrooms", "Wet Areas", "Residential", "Commercial"],
    description: "Historical green-inspired decorative design with Evo Dry Technology",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
    ],
  },
  {
    id: 69,
    slug: "decorative-mountain",
    name: "Mountain - Evo Dry Technology",
    code: "65601",
    category: "decorative",
    finish: "matt",
    price: 60,
    unit: "sqft",
    size: "800x2400mm",
    thickness: "15mm",
    applications: ["Walls", "Feature Areas", "Bathrooms", "Wet Areas", "Residential", "Commercial"],
    description: "Mountain-inspired decorative design with Evo Dry Technology",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
    ],
  },
  // Tiles - Wood Look (Cottage Series) - 20x120cm
  {
    id: 70,
    slug: "cottage-walnut",
    name: "Cottage Walnut",
    code: "1450",
    category: "tiles",
    finish: "matt",
    price: 40,
    unit: "sqft",
    size: "20x120cm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Authentic walnut wood look porcelain tile, 6-face design for versatile installation",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
    ],
  },
  {
    id: 71,
    slug: "cottage-ash",
    name: "Cottage Ash",
    code: "1400",
    category: "tiles",
    finish: "matt",
    price: 40,
    unit: "sqft",
    size: "20x120cm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Natural ash wood look porcelain tile, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
    ],
  },
  {
    id: 72,
    slug: "cottage-carbon",
    name: "Cottage Carbon",
    code: "1410",
    category: "tiles",
    finish: "matt",
    price: 42,
    unit: "sqft",
    size: "20x120cm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Dark carbon wood look porcelain tile, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
    ],
  },
  {
    id: 73,
    slug: "cottage-oak",
    name: "Cottage Oak",
    code: "1420",
    category: "tiles",
    finish: "matt",
    price: 40,
    unit: "sqft",
    size: "20x120cm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Classic oak wood look porcelain tile, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
    ],
  },
  {
    id: 74,
    slug: "cottage-almond",
    name: "Cottage Almond",
    code: "1430",
    category: "tiles",
    finish: "matt",
    price: 40,
    unit: "sqft",
    size: "20x120cm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Warm almond wood look porcelain tile, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
    ],
  },
  {
    id: 75,
    slug: "cottage-cherry",
    name: "Cottage Cherry",
    code: "1440",
    category: "tiles",
    finish: "matt",
    price: 41,
    unit: "sqft",
    size: "20x120cm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Rich cherry wood look porcelain tile, 6-face design",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
    ],
  },
  {
    id: 76,
    slug: "cottage-white",
    name: "Cottage White",
    code: "1460",
    category: "tiles",
    finish: "matt",
    price: 40,
    unit: "sqft",
    size: "20x120cm",
    sixFace: true,
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Light white wood look porcelain tile, 6-face design",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
    ],
  },
  // Tiles - Standard Formats
  {
    id: 77,
    slug: "hardstone-dark-gray",
    name: "Hardstone Dark Gray",
    code: "5080",
    category: "tiles",
    finish: "matt",
    price: 35,
    unit: "sqft",
    size: "40x40cm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Dark gray hardstone porcelain tile for versatile applications",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
    ],
  },
  {
    id: 78,
    slug: "hardstone-light-gray",
    name: "Hardstone Light Gray",
    code: "5090",
    category: "tiles",
    finish: "matt",
    price: 35,
    unit: "sqft",
    size: "40x40cm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Light gray hardstone porcelain tile for versatile applications",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_15.png',
    ],
  },
  {
    id: 79,
    slug: "slate-light-gray",
    name: "Slate Light Gray",
    code: "6010",
    category: "tiles",
    finish: "matt",
    price: 38,
    unit: "sqft",
    size: "60x60cm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Light gray slate-inspired porcelain tile",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_17.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_19.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_21.png',
    ],
  },
  {
    id: 80,
    slug: "slate-ivory",
    name: "Slate Ivory",
    code: "6020",
    category: "tiles",
    finish: "matt",
    price: 38,
    unit: "sqft",
    size: "60x60cm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Ivory slate-inspired porcelain tile",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_23.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_25.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_27.png',
    ],
  },
  {
    id: 81,
    slug: "slate-mid-gray",
    name: "Slate Mid Gray",
    code: "6030",
    category: "tiles",
    finish: "matt",
    price: 38,
    unit: "sqft",
    size: "60x60cm",
    applications: ["Floors", "Walls", "Residential", "Commercial"],
    description: "Mid gray slate-inspired porcelain tile",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_29.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_3.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_31.png',
    ],
  },
  // Swimming Pool Tiles - Starwave Series
  {
    id: 82,
    slug: "starwave-48x48-dark-blue",
    name: "Starwave Series - 48x48mm Dark Blue Mix",
    code: "SP-MCS650721",
    category: "pool",
    finish: "polished",
    price: 55,
    unit: "sqft",
    size: "48x48x6mm (306x306x6mm sheet)",
    applications: ["Swimming Pools", "Walls", "Floors", "Pool Surrounds", "Kitchen Backsplashes", "Bathroom Features", "Outdoor"],
    description: "Crystalline glazed porcelain capturing starlight and ocean waves. Dark blue mix pattern with varying shades reflecting shimmering light. Perfect for indoor and outdoor pool applications.",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_33.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_35.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_37.png',
    ],
  },
  {
    id: 83,
    slug: "starwave-48x48-medium-blue",
    name: "Starwave Series - 48x48mm Medium Blue Mix",
    code: "SP-MCS650722",
    category: "pool",
    finish: "polished",
    price: 55,
    unit: "sqft",
    size: "48x48x6mm (306x306x6mm sheet)",
    applications: ["Swimming Pools", "Walls", "Floors", "Pool Surrounds", "Kitchen Backsplashes", "Bathroom Features", "Outdoor"],
    description: "Crystalline glazed porcelain with medium blue mix pattern. Expresses harmony between nature's calm and movement.",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_39.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_41.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_43.png',
    ],
  },
  {
    id: 84,
    slug: "starwave-48x48-light-blue",
    name: "Starwave Series - 48x48mm Light Blue Mix",
    code: "SP-MCS650723",
    category: "pool",
    finish: "polished",
    price: 55,
    unit: "sqft",
    size: "48x48x6mm (306x306x6mm sheet)",
    applications: ["Swimming Pools", "Walls", "Floors", "Pool Surrounds", "Kitchen Backsplashes", "Bathroom Features", "Outdoor"],
    description: "Crystalline glazed porcelain with light blue mix pattern. Creates a sense of infinite depth and elegance.",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_5.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_7.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_9.png',
    ],
  },
  {
    id: 85,
    slug: "starwave-25x25-turquoise",
    name: "Starwave Series - 25x25mm Turquoise Mix",
    code: "SP-MCS630503",
    category: "pool",
    finish: "polished",
    price: 55,
    unit: "sqft",
    size: "25x25x5mm (300x300x5mm sheet)",
    applications: ["Swimming Pools", "Walls", "Floors", "Pool Surrounds", "Kitchen Backsplashes", "Bathroom Features", "Outdoor"],
    description: "Crystalline glazed porcelain with turquoise mix pattern. Smaller format for detailed installations.",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_10.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_13.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_16.png',
    ],
  },
  {
    id: 86,
    slug: "starwave-25x25-sky-blue",
    name: "Starwave Series - 25x25mm Sky Blue Mix",
    code: "SP-MCS630501",
    category: "pool",
    finish: "polished",
    price: 55,
    unit: "sqft",
    size: "25x25x5mm (300x300x5mm sheet)",
    applications: ["Swimming Pools", "Walls", "Floors", "Pool Surrounds", "Kitchen Backsplashes", "Bathroom Features", "Outdoor"],
    description: "Crystalline glazed porcelain with sky blue mix pattern. Like gazing into a starry sea.",
    images: [
      '/images/products/60X120 15mm full body timelesstouchceramics_19.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_4.png',
      '/images/products/60X120 15mm full body timelesstouchceramics_7.png',
    ],
  },
  {
    id: 87,
    slug: "starwave-25x25-deep-blue",
    name: "Starwave Series - 25x25mm Deep Blue Mix",
    code: "SP-MCS630502",
    category: "pool",
    finish: "polished",
    price: 55,
    unit: "sqft",
    size: "25x25x5mm (300x300x5mm sheet)",
    applications: ["Swimming Pools", "Walls", "Floors", "Pool Surrounds", "Kitchen Backsplashes", "Bathroom Features", "Outdoor"],
    description: "Crystalline glazed porcelain with deep blue mix pattern. Captures the poetic blend of starlight and ocean waves.",
    images: [
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_1.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_11.png',
      '/images/products/60x120cm 60x60cm Matt timelesstouchceramics_13.png',
    ],
  },
];

export const categories = [
  "stone-look",
  "marble-look",
  "modern-look",
  "decorative",
  "tiles",
  "pool",
];
export const finishes = ["polished", "matt"];
