import { defineField, defineType } from "sanity";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "basic", title: "Basic Info", default: true },
    { name: "categorization", title: "Categorization" },
    { name: "specifications", title: "Specifications" },
    { name: "features", title: "Features" },
    { name: "media", title: "Media" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      group: "basic",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "basic",
      options: {
        source: "name",
        maxLength: 200,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "code",
      title: "Product Code",
      type: "string",
      group: "basic",
      description: "SKU or product code",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      group: "basic",
      rows: 4,
    }),
    defineField({
      name: "price",
      title: "Price",
      type: "number",
      group: "basic",
      validation: (Rule) => Rule.required().positive(),
    }),
    defineField({
      name: "unit",
      title: "Unit",
      type: "string",
      group: "basic",
      description: "Price unit (e.g., per sqm, per piece)",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "mainCategory",
      title: "Main Category",
      type: "reference",
      to: [{ type: "mainCategory" }],
      group: "categorization",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "designStyle",
      title: "Design Style",
      type: "reference",
      to: [{ type: "designStyle" }],
      group: "categorization",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "finish",
      title: "Finish",
      type: "reference",
      to: [{ type: "finish" }],
      group: "categorization",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "applications",
      title: "Applications",
      type: "array",
      of: [{ type: "reference", to: [{ type: "application" }] }],
      group: "categorization",
    }),
    defineField({
      name: "catalogues",
      title: "Catalogues",
      type: "array",
      of: [{ type: "reference", to: [{ type: "catalogue" }] }],
      group: "categorization",
    }),
    defineField({
      name: "sizes",
      title: "Sizes",
      type: "array",
      of: [{ type: "reference", to: [{ type: "size" }] }],
      group: "specifications",
    }),
    defineField({
      name: "thickness",
      title: "Thickness",
      type: "reference",
      to: [{ type: "thickness" }],
      group: "specifications",
    }),
    defineField({
      name: "bookmatch",
      title: "Bookmatch",
      type: "boolean",
      group: "features",
      initialValue: false,
    }),
    defineField({
      name: "sixFace",
      title: "Six Face",
      type: "boolean",
      group: "features",
      initialValue: false,
    }),
    defineField({
      name: "fullBody",
      title: "Full Body",
      type: "boolean",
      group: "features",
      initialValue: false,
    }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      of: [
        {
          type: "image",
          options: {
            hotspot: true,
          },
        },
      ],
      group: "media",
      validation: (Rule) => Rule.required().min(1),
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "code",
      media: "images.0",
    },
  },
});
